CREATE TABLE "dvds" (
	"id" serial PRIMARY KEY,
	"title" text NOT NULL,
	"year" text,
	"director" text,
	"genre" text,
	"cast" text,
	"plot" text,
	"runtime" text,
	"rating" text,
	"imdb_rating" text,
	"imdb_id" text,
	"poster_url" text,
	"shelf" text,
	"barcode" text,
	"quantity" integer DEFAULT 1 NOT NULL,
	"available" boolean DEFAULT true NOT NULL,
	"details_source" text DEFAULT 'catalogue' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);


INSERT INTO "dvds" ("title", "director", "genre", "shelf") VALUES
('Adele Live at the Royal Albert Hall', 'Various', 'Music/Concert', 'Modern Music'),
('Alfie Live: The Bring Him Home Tour', 'Various', 'Music/Concert', 'Modern Music'),
('Amici Forever', 'Various', 'Music/Concert', 'Modern Music'),
('Bachelor Lounge', 'Various', 'Music/Concert', 'Modern Music'),
('Barbra Streisand Live at the Village Vanguard', 'Various', 'Music/Concert', 'Modern Music'),
('Billy Joel: The Ultimate Collection', 'Various', 'Music/Concert', 'Modern Music'),
('Brian Wilson Presents Smile', 'Various', 'Music/Concert', 'Modern Music'),
('Bruce Springsteen: Storytellers', 'Various', 'Music/Concert', 'Modern Music'),
('Carole King in Concert', 'Various', 'Music/Concert', 'Modern Music'),
('Dionne Warwick & Burt Bacharach', 'Various', 'Music/Concert', 'Modern Music'),
('Fleetwood Mac: The Dance', 'Various', 'Music/Concert', 'Modern Music'),
('Frank Sinatra: Ol'' Blue Eyes Is Back', 'Various', 'Music/Concert', 'Modern Music'),
('James Last: A World of Music', 'Various', 'Music/Concert', 'Modern Music'),
('James Last: Gentleman of Music', 'Various', 'Music/Concert', 'Modern Music'),
('Judith Durham: The Seekers - 25 Year Reunion', 'Various', 'Music/Concert', 'Modern Music'),
('Ladies & Gentlemen... Sole Mio: Live in Concert', 'Various', 'Music/Concert', 'Modern Music'),
('Louis Armstrong & Benny Goodman', 'Various', 'Music/Concert', 'Modern Music'),
('Neil Young: Crazy Horse - Rust Never Sleeps', 'Various', 'Music/Concert', 'Modern Music'),
('Ray Charles in Concert', 'Various', 'Music/Concert', 'Modern Music'),
('Simon & Garfunkel: The Concert in Central Park', 'Various', 'Music/Concert', 'Modern Music'),
('Sinatra: All or Nothing at All', 'Alex Gibney', 'Music/Documentary', 'Modern Music'),
('Sonny & Cher', 'Various', 'Music/Concert', 'Modern Music'),
('The Cliff Richard Movie Collection', 'Various', 'Music/Concert', 'Modern Music'),
('The Divas Collection', 'Various', 'Music/Concert', 'Modern Music'),
('The Frank Sinatra Show with Dean Martin & Bing Crosby', 'Various', 'Music/Concert', 'Modern Music'),
('The Rat Pack Story', 'Various', 'Music/Documentary', 'Modern Music'),
('Tony Bennett''s New York', 'Various', 'Music/Concert', 'Modern Music'),
('Westlife: The Number Ones Tour', 'Various', 'Music/Concert', 'Modern Music'),
('Westlife: Unbreakable - The Greatest Hits Vol. 1', 'Various', 'Music/Concert', 'Modern Music'),
('Yusuf: Roadsinger Live 2010', 'Various', 'Music/Concert', 'Modern Music'),
('3x''s Horse: A Man Called Sledge / Hombre / Valance', 'Various', 'Western', 'Movies'),
('A Fistful of Dollars', 'Sergio Leone', 'Western', 'Movies'),
('A Star is Born', 'Frank Pierson', 'Drama/Musical', 'Movies'),
('A Walk in the Clouds', 'Alfonso Arau', 'Romance/Drama', 'Movies'),
('Aces High', 'Jack Gold', 'War/Drama', 'Movies'),
('Against All Odds', 'Taylor Hackford', 'Action/Thriller', 'Movies'),
('Agatha Christie: Marple - The Body in the Library', 'Various', 'TV Crime/Mystery', 'Movies'),
('All the King''s Men', 'Steven Zaillian', 'Drama/Thriller', 'Movies'),
('Allegheny Uprising', 'William A. Seiter', 'Western/Adventure', 'Movies'),
('Amadeus: Director''s Cut', 'Milos Forman', 'Biography/Drama', 'Movies'),
('American Gangster', 'Ridley Scott', 'Crime/Drama', 'Movies'),
('An Andy Hardy', 'Various', 'Comedy/Classics', 'Movies'),
('Andre Rieu: Christmas in London', 'Various', 'Music/Concert', 'Movies'),
('Angels', 'Various', 'TV Drama', 'Movies'),
('Anne of the Thousand Days', 'Charles Jarrott', 'Biography/Drama', 'Movies'),
('Anonymous', 'Roland Emmerich', 'Drama/Thriller', 'Movies'),
('Any Given Sunday', 'Oliver Stone', 'Drama/Sport', 'Movies'),
('Apache', 'Robert Aldrich', 'Western', 'Movies'),
('Apache Rifles', 'William Witney', 'Western', 'Movies'),
('April Love', 'Henry Levin', 'Musical/Romance', 'Movies'),
('Are You Being Served?: Series Two', 'Various', 'TV Comedy', 'Movies'),
('Around the World in 80 Days', 'Michael Anderson', 'Adventure/Comedy', 'Movies'),
('Around the World in 80 Days / Rush Hour', 'Various', 'Action/Adventure', 'Movies'),
('Austin Powers', 'Jay Roach', 'Comedy', 'Movies'),
('Avalanche', 'Corey Allen', 'Action/Thriller', 'Movies'),
('Avatar', 'James Cameron', 'Sci-Fi/Action', 'Movies'),
('Battle at Apache Pass', 'George Sherman', 'Western', 'Movies'),
('Ben-Hur', 'William Wyler', 'Adventure/Drama', 'Movies'),
('Bendy: Becoming Jane', 'Julian Jarrold', 'Biography/Romance', 'Movies'),
('Bernardine', 'Henry Levin', 'Musical/Romance', 'Movies'),
('Bertie & Elizabeth: A Story of Love and Destiny', 'Giles Foster', 'Biography/Drama', 'Movies'),
('Billy the Kid Returns / Saga of Death Valley / Days of Jesse James', 'Various', 'Western', 'Movies'),
('Bite the Bullet / Geronimo', 'Various', 'Western', 'Movies'),
('Black Dawn', 'Alexander Gruszynski', 'Action', 'Movies'),
('Blazing Saddles', 'Mel Brooks', 'Western/Comedy', 'Movies'),
('Boychoir', 'François Girard', 'Drama/Music', 'Movies'),
('Brassed Off!', 'Mark Herman', 'Comedy/Drama', 'Movies'),
('Bride & Prejudice', 'Gurinder Chadha', 'Romance/Musical', 'Movies'),
('Broken Embraces', 'Pedro Almodóvar', 'Drama/Thriller', 'Movies'),
('Brothers in Arms', 'Jean-Claude La Marre', 'Western', 'Movies'),
('Butch Cassidy and the Sundance Kid', 'George Roy Hill', 'Western/Action', 'Movies'),
('California Suite', 'Herbert Ross', 'Comedy/Drama', 'Movies'),
('Campion: The Complete First Series', 'Various', 'TV Crime/Mystery', 'Movies'),
('Campion: The Complete Second Series', 'Various', 'TV Crime/Mystery', 'Movies'),
('Captain Corelli''s Mandolin', 'John Madden', 'Drama/Romance', 'Movies'),
('Castle Keep', 'Sydney Pollack', 'War/Drama', 'Movies'),
('Casualties of War', 'Brian De Palma', 'War/Drama', 'Movies'),
('Chase', 'Arthur Penn', 'Crime/Drama', 'Movies'),
('Christmas Greats!', 'Various', 'Holiday/Music', 'Movies'),
('Citizen Kane', 'Orson Welles', 'Drama/Mystery', 'Movies'),
('City Hall', 'Harold Becker', 'Drama/Thriller', 'Movies'),
('Clear and Present Danger', 'Phillip Noyce', 'Action/Thriller', 'Movies'),
('Contact', 'Robert Zemeckis', 'Sci-Fi/Drama', 'Movies'),
('Crimes of the Heart', 'Bruce Beresford', 'Comedy/Drama', 'Movies'),
('Custer of the West', 'Robert Siodmak', 'Western', 'Movies'),
('Doctor Who', 'Various', 'TV Sci-Fi', 'Movies'),
('Donnie Darko', 'Richard Kelly', 'Sci-Fi/Thriller', 'Movies'),
('Dookudu', 'Srinu Vaitla', 'Action/Comedy', 'Movies'),
('El Cid', 'Anthony Mann', 'Adventure/Drama', 'Movies'),
('Elizabeth', 'Shekhar Kapur', 'Biography/Drama', 'Movies'),
('Elmer Gantry', 'Richard Brooks', 'Drama', 'Movies'),
('Enemy Gates', 'Jean-Jacques Annaud', 'War/Drama', 'Movies'),
('Eragon', 'Stefen Fangmeier', 'Fantasy/Adventure', 'Movies'),
('Escape from Sobibor', 'Jack Gold', 'War/Drama', 'Movies'),
('Eversmile New Jersey', 'Carlos Sorín', 'Comedy/Drama', 'Movies'),
('Evita', 'Alan Parker', 'Biography/Musical', 'Movies'),
('Five Card Stud', 'Henry Hathaway', 'Western', 'Movies'),
('Flame and Citron', 'Ole Christian Madsen', 'War/Drama', 'Movies'),
('Four Weddings and a Funeral', 'Mike Newell', 'Comedy/Romance', 'Movies'),
('Fred Astaire Collection 1', 'Various', 'Musical/Classics', 'Movies'),
('Gettin'' Square', 'Jonathan Teplitzky', 'Comedy/Crime', 'Movies'),
('Giant', 'George Stevens', 'Drama/Western', 'Movies'),
('Gunfight at the O.K. Corral', 'John Sturges', 'Western', 'Movies'),
('Hancock', 'Peter Berg', 'Action/Comedy', 'Movies'),
('Heaven is for Real', 'Randall Wallace', 'Drama/Family', 'Movies'),
('Hell in the Pacific', 'John Boorman', 'War/Drama', 'Movies'),
('High Noon', 'Fred Zinnemann', 'Western', 'Movies'),
('High Society', 'Charles Walters', 'Musical/Comedy', 'Movies'),
('Hollywood Gold Series: The Way Ahead', 'Carol Reed', 'War/Drama', 'Movies'),
('Inglourious Basterds', 'Quentin Tarantino', 'War/Drama', 'Movies'),
('It''s a Wonderful Life', 'Frank Capra', 'Drama/Family', 'Movies'),
('James Stewart: Made for Each Other / Pot o'' Gold', 'Various', 'Comedy/Romance', 'Movies'),
('Jane Eyre', 'Robert Stevenson', 'Drama/Romance', 'Movies'),
('Jerry Maguire', 'Cameron Crowe', 'Comedy/Romance', 'Movies'),
('Jesus of Nazareth', 'Franco Zeffirelli', 'Religious/Drama', 'Movies'),
('John Wayne Collector''s Classics Vol 3', 'Various', 'Western', 'Movies'),
('John Wayne: The Trail Beyond / West of the Divide', 'Various', 'Western', 'Movies'),
('John Wayne: Winds of the Wasteland', 'Mack V. Wright', 'Western', 'Movies'),
('Jules Dassin''s Rififi', 'Jules Dassin', 'Crime/Thriller', 'Movies'),
('King of Kings', 'Nicholas Ray', 'Biography/Drama', 'Movies'),
('La Spagnola', 'Steve Jacobs', 'Comedy/Drama', 'Movies'),
('La Vie en Rose', 'Olivier Dahan', 'Biography/Musical', 'Movies'),
('Last Train from Gun Hill', 'John Sturges', 'Western', 'Movies'),
('Mae West: 6 Disc Box Set', 'Various', 'Comedy/Classics', 'Movies'),
('Man from Alamo', 'Budd Boetticher', 'Western', 'Movies'),
('Mao''s Last Dancer', 'Bruce Beresford', 'Biography/Drama', 'Movies'),
('Marley & Me', 'David Frankel', 'Comedy/Drama', 'Movies'),
('Marty', 'Delbert Mann', 'Drama/Romance', 'Movies'),
('Meet the Parents', 'Jay Roach', 'Comedy', 'Movies'),
('Meet the Parents: Platinum Collection', 'Jay Roach', 'Comedy', 'Movies'),
('Million Dollar Baby', 'Clint Eastwood', 'Drama/Sport', 'Movies'),
('Mirror Mirror', 'Tarsem Singh', 'Fantasy/Adventure', 'Movies'),
('Monster-in-Law', 'Robert Luketic', 'Comedy/Romance', 'Movies'),
('Monty Python''s The Meaning of Life', 'Terry Jones', 'Comedy', 'Movies'),
('Mrs Caldicot''s Cabbage War', 'Ian Sharp', 'Comedy/Drama', 'Movies'),
('My Afternoons with Margueritte', 'Jean Becker', 'Comedy/Drama', 'Movies'),
('My Best Friend''s Wedding', 'P.J. Hogan', 'Comedy/Romance', 'Movies'),
('Napoleon Dynamite', 'Jared Hess', 'Comedy', 'Movies'),
('No Strings Attached', 'Ivan Reitman', 'Comedy/Romance', 'Movies'),
('Not the Albino', 'Various', 'Comedy', 'Movies'),
('Notting Hill', 'Roger Michell', 'Comedy/Romance', 'Movies'),
('Ocean''s Eleven', 'Steven Soderbergh', 'Crime/Thriller', 'Movies'),
('One Day Before Chance', 'Various', 'Drama', 'Movies'),
('P.I. Tchaikovsky', 'Various', 'Documentary', 'Movies'),
('Pearl Harbor', 'Michael Bay', 'War/Drama', 'Movies'),
('Pirates of the Caribbean 4: On Stranger Tides', 'Rob Marshall', 'Adventure/Fantasy', 'Movies'),
('Punchline', 'David Seltzer', 'Comedy/Drama', 'Movies'),
('Purple Violets', 'Edward Burns', 'Comedy/Romance', 'Movies'),
('Purple Violets / Eversmile New Jersey', 'Various', 'Comedy/Romance', 'Movies'),
('Quantum of Solace', 'Marc Forster', 'Action/Thriller', 'Movies'),
('Rage at Dawn', 'Tim Whelan', 'Western', 'Movies'),
('Rio Bravo', 'Howard Hawks', 'Western', 'Movies'),
('Rio Grande', 'John Ford', 'Western/War', 'Movies'),
('Riverdance', 'John McColgan', 'Music/Dance', 'Movies'),
('Road to Perdition', 'Sam Mendes', 'Crime/Drama', 'Movies'),
('Robin Hood: Prince of Thieves', 'Kevin Reynolds', 'Adventure/Action', 'Movies'),
('Rocketman', 'Dexter Fletcher', 'Biography/Musical', 'Movies'),
('Rogue Male', 'Clive Donner', 'Thriller/Drama', 'Movies'),
('Ronnie Barker: Classic Comedy', 'Various', 'TV Comedy', 'Movies'),
('Rumor Has It...', 'Rob Reiner', 'Comedy/Romance', 'Movies'),
('Run All Night', 'Jaume Collet-Serra', 'Action/Thriller', 'Movies'),
('Rush Hour', 'Brett Ratner', 'Action/Comedy', 'Movies'),
('Saddle Valentine', 'Various', 'Western', 'Movies'),
('Seducing Doctor Lewis', 'Jean-François Pouliot', 'Comedy', 'Movies'),
('Separate Lies', 'Julian Fellowes', 'Drama/Romance', 'Movies'),
('Six Shooter Classics: Broken Arrow', 'Delmer Daves', 'Western', 'Movies'),
('Six Shooter Classics: Ulzana''s Raid', 'Robert Aldrich', 'Western', 'Movies'),
('Skyfall', 'Sam Mendes', 'Action/Thriller', 'Movies'),
('Sniper: Special Ops', 'Fred Olen Ray', 'Action/War', 'Movies'),
('Soldiers Without Guns', 'Will Watson', 'Documentary', 'Movies'),
('Songcatcher', 'Maggie Greenwald', 'Drama/Music', 'Movies'),
('South of Heaven / West of Hell', 'Various', 'Western', 'Movies'),
('Talk to Her', 'Pedro Almodóvar', 'Drama', 'Movies'),
('The Alamo', 'John Wayne', 'Western/War', 'Movies'),
('The Assassination of Jesse James by the Coward Robert Ford', 'Andrew Dominik', 'Western/Drama', 'Movies'),
('The Aviator', 'Martin Scorsese', 'Biography/Drama', 'Movies'),
('The Barbarian Invasions', 'Denys Arcand', 'Comedy/Drama', 'Movies'),
('The Bells of San Angelo', 'William Witney', 'Western', 'Movies'),
('The Big Man', 'David Leland', 'Crime/Drama', 'Movies'),
('The Big Stampede', 'Tenny Wright', 'Western', 'Movies'),
('The Big Stampede / Colorado', 'Various', 'Western', 'Movies'),
('The Birdcage', 'Mike Nichols', 'Comedy', 'Movies'),
('The Book Thief', 'Brian Percival', 'Drama/War', 'Movies'),
('The Boy in the Plastic Bubble', 'Randal Kleiser', 'Drama/Romance', 'Movies'),
('The Break-Up', 'Peyton Reed', 'Comedy/Romance', 'Movies'),
('The Comancheros', 'Michael Curtiz', 'Western', 'Movies'),
('The Concert', 'Radu Mihăileanu', 'Comedy/Drama', 'Movies'),
('The Concorde... Airport ''79', 'David Lowell Rich', 'Action/Thriller', 'Movies'),
('The Day Will Dawn', 'Harold French', 'War/Drama', 'Movies'),
('The Exorcism of Emily Rose', 'Scott Derrickson', 'Horror/Drama', 'Movies'),
('The Far Country', 'Anthony Mann', 'Western', 'Movies'),
('The Four Seasons', 'Alan Alda', 'Comedy/Drama', 'Movies'),
('The Girl with the Dragon Tattoo', 'David Fincher', 'Crime/Thriller', 'Movies'),
('The Gold Rush', 'Charlie Chaplin', 'Comedy/Classics', 'Movies'),
('The Good, the Bad and the Ugly', 'Sergio Leone', 'Western', 'Movies'),
('The Great Gatsby', 'Baz Luhrmann', 'Drama/Romance', 'Movies'),
('The Hudsucker Proxy', 'Coen Brothers', 'Comedy/Fantasy', 'Movies'),
('The Hundred-Year-Old Man Who Climbed Out the Window and Disappeared', 'Felix Herngren', 'Comedy/Adventure', 'Movies'),
('The Hunted', 'William Friedkin', 'Action/Thriller', 'Movies'),
('The Hurricane', 'Norman Jewison', 'Biography/Drama', 'Movies'),
('The Informant!', 'Steven Soderbergh', 'Comedy/Drama', 'Movies'),
('The Joy Luck Club', 'Wayne Wang', 'Drama', 'Movies'),
('The Last of the Mohicans', 'Michael Mann', 'Action/Adventure', 'Movies'),
('The Left Handed Gun', 'Arthur Penn', 'Western', 'Movies'),
('The Man from Utah', 'Robert N. Bradbury', 'Western', 'Movies'),
('The Party', 'Blake Edwards', 'Comedy', 'Movies'),
('The Punisher', 'Jonathan Hensleigh', 'Action/Crime', 'Movies'),
('The Roarer', 'Various', 'Western', 'Movies'),
('The Saddest Music in the World', 'Guy Maddin', 'Comedy/Musical', 'Movies'),
('The Shooting', 'Monte Hellman', 'Western', 'Movies'),
('The Silver Fleet', 'Vernon Sewell', 'War/Drama', 'Movies'),
('The Soloist', 'Joe Wright', 'Biography/Drama', 'Movies'),
('The Survivors', 'Michael Ritchie', 'Comedy', 'Movies'),
('The Taking of Pelham 123', 'Tony Scott', 'Action/Thriller', 'Movies'),
('The Ultimate Bourne Collection', 'Various', 'Action/Thriller', 'Movies'),
('The Very Best of...', 'Various', 'Music/Concert', 'Movies'),
('The War Collection Volume 2', 'Various', 'War', 'Movies'),
('The World''s Fastest Indian', 'Roger Donaldson', 'Biography/Drama', 'Movies'),
('This Must Be the Place', 'Paolo Sorrentino', 'Comedy/Drama', 'Movies'),
('Those Magnificent Men in Their Flying Machines', 'Ken Annakin', 'Adventure/Comedy', 'Movies'),
('Till the Clouds Roll By', 'Richard Whorf', 'Musical/Biography', 'Movies'),
('To Sir, with Love', 'James Clavell', 'Drama', 'Movies'),
('To Sir, with Love / Guess Who''s Coming to Dinner', 'Various', 'Drama', 'Movies'),
('Two Men in a Tinnie', 'Various', 'Documentary', 'Movies'),
('Vento Do Oeste / Billy the Kid', 'Various', 'Western', 'Movies'),
('When Elizabeth the Queen Mother: A Woman of Her Century', 'Various', 'Documentary', 'Movies'),
('Without Honor', 'Irving Pichel', 'Western', 'Movies'),
('Wuthering Heights', 'William Wyler', 'Drama/Romance', 'Movies'),
('Zulu', 'Cy Endfield', 'War/Drama', 'Movies'),
('30 Years of Maximum R&B Live', 'Various', 'Music/Concert', 'Music'),
('Bee Gees: One Night Only', 'Various', 'Music/Concert', 'Music'),
('Cliff Richard: The Shadows 2009', 'Various', 'Music/Concert', 'Music'),
('Cream', 'Various', 'Music/Documentary', 'Music'),
('Diana Krall: Live at the Montreal Jazz Festival', 'Various', 'Music/Concert', 'Music'),
('Eagles: Hell Freezes Over', 'Beth McCarthy-Miller', 'Music/Concert', 'Music'),
('Elvis Live: The 25th Anniversary Concert', 'Various', 'Music/Concert', 'Music'),
('Eric Burdon: The Animals Greatest Hits Live', 'Various', 'Music/Concert', 'Music'),
('Jimi Hendrix / Led Zeppelin: Woodstock - The Director''s Cut', 'Various', 'Music/Concert', 'Music'),
('John Denver: The Wildlife Concert', 'Various', 'Music/Concert', 'Music'),
('Liberace: Live in Las Vegas Hilton', 'Various', 'Music/Concert', 'Music'),
('Liberace: Live in London', 'Various', 'Music/Concert', 'Music'),
('Liberace: Live in Vegas', 'Various', 'Music/Concert', 'Music'),
('Liberace: Valentine''s Day Live in Las Vegas Hilton', 'Various', 'Music/Concert', 'Music'),
('Live from Austin TX: Johnny Cash', 'Various', 'Music/Concert', 'Music'),
('Michael Jackson''s This Is It', 'Kenny Ortega', 'Music/Documentary', 'Music'),
('Pink Floyd: In Concert P.U.L.S.E.', 'Various', 'Music/Concert', 'Music'),
('Red Rocks Live: Neil Young - Friends & Relatives', 'Various', 'Music/Concert', 'Music'),
('Spandau Ballet: The Last Waltz', 'Various', 'Music/Concert', 'Music'),
('The Band: The Authorized Biography', 'Various', 'Music/Documentary', 'Music'),
('The Beatles: 1', 'Various', 'Music/Concert', 'Music'),
('The Beatles: Yesterday', 'Various', 'Music/Documentary', 'Music'),
('Year of the Horse', 'Jim Jarmusch', 'Music/Documentary', 'Music'),
('Are You Being Served?: Series Four', 'Various', 'TV Comedy', 'TV Series'),
('Blackadder 2', 'Various', 'TV Comedy', 'TV Series'),
('Call the Midwife: Series (2 DISCS)', 'Various', 'TV Drama', 'TV Series'),
('Call the Midwife: Series Two', 'Various', 'TV Drama', 'TV Series'),
('Death Us Do Part', 'Various', 'TV Comedy', 'TV Series'),
('Dick Emery', 'Various', 'TV Comedy', 'TV Series'),
('Father Ted: The Definitive Collection', 'Various', 'TV Comedy', 'TV Series'),
('Flight of the Conchords: The Complete First Season', 'Various', 'TV Comedy/Musical', 'TV Series'),
('Forever Summer with Nigella', 'Various', 'TV Cooking', 'TV Series'),
('Lark Rise to Candleford: Complete Series', 'Various', 'TV Drama', 'TV Series'),
('Miss Fisher''s Murder Mysteries: Series 1 Volume 1', 'Various', 'TV Crime/Mystery', 'TV Series'),
('Miss Fisher''s Murder Mysteries: Series 1 Volume 2', 'Various', 'TV Crime/Mystery', 'TV Series'),
('Monty Python''s And Now For Something Completely Different', 'Ian MacNaughton', 'TV Comedy', 'TV Series'),
('Mother & Son: Volume 3', 'Various', 'TV Comedy', 'TV Series'),
('Mrs. Brown''s Boys: Season One', 'Ben Kellett', 'TV Comedy', 'TV Series'),
('Mrs. Brown''s Boys: Season Two', 'Ben Kellett', 'TV Comedy', 'TV Series'),
('Peanuts: Lucy', 'Various', 'TV Animation', 'TV Series'),
('Penny Hill: Double Helpings!', 'Various', 'TV Comedy', 'TV Series'),
('Peter Kay''s Car Share', 'Peter Kay', 'TV Comedy', 'TV Series'),
('Sex and the City: The Complete Season 5', 'Various', 'TV Comedy/Drama', 'TV Series'),
('Some Mothers Do ''Ave ''Em: The Complete Second Series', 'Various', 'TV Comedy', 'TV Series'),
('Steptoe & Son: The Complete Second Series', 'Various', 'TV Comedy', 'TV Series'),
('Steptoe and Son: Series Two', 'Various', 'TV Comedy', 'TV Series'),
('Tenko: Series 1 Episodes 1-5', 'Various', 'TV Drama', 'TV Series'),
('The Best of British Comedy', 'Various', 'TV Comedy', 'TV Series'),
('The Best of British Comedy: Archive Collection', 'Various', 'TV Comedy', 'TV Series'),
('The Best of Charlie''s Angels TV', 'Various', 'TV Crime/Action', 'TV Series'),
('The Best of Peter Cook & Dudley Moore', 'Various', 'TV Comedy', 'TV Series'),
('The Best of Spike Milligan', 'Various', 'TV Comedy', 'TV Series'),
('The Dick Cavett Show: Comic Legends', 'Various', 'TV Comedy', 'TV Series'),
('The Lucy Show: Volume 6', 'Various', 'TV Comedy', 'TV Series'),
('The Tudors: The Complete Second Season', 'Various', 'TV Drama', 'TV Series'),
('Till Death Us Do Part: The Complete 1972 and 1974 Series', 'Various', 'TV Comedy', 'TV Series');
